services:
  - type: web
    name: car-parking-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
